# fly.toml app configuration file generated for agrostats-api on 2023-06-26T10:39:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "agrostats-api"
primary_region = "mad"

[env]
  JAVA_OPTS = "-XX:MaxRAM=70m"
  SERVER_FORWARD_HEADERS_STRATEGY = "NATIVE"
  SPRING_PROFILES_ACTIVE = "flyio"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
